FROM node:latest
MAINTAINER Ian Peake <ian.peake@rmit.edu.au>

RUN useradd -ms /bin/bash user
#RUN setcap 'cap_net_bind_service=+ep' `which node`
RUN chown -R user /home/user

USER user
WORKDIR /home/user

#VOLUME /data

EXPOSE 80

RUN git clone https://github.com/martin-sean/real-time-transportation-api
RUN cd real-time-transportation-api && npm install

USER root
RUN chown -R user /home/user

USER user
WORKDIR /home/user/real-time-transportation-api
